alias bd=". bd -s"

PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting
## Tizen SDK configuration
# This is generated by Tizen SDK. Please do not modify by yourself.
# Set sdb environment path
export PATH=$PATH:/Users/mattschmulen/tizen-sdk/tools
## End Tizen SDK configuration
